---
title: Projects
---

## Hand Hygiene Complaince: University Hospital 

Currently working on a quality improvement project with the infection prevention team at University Hospitals located in Cleveland, Ohio. The focus of the project is to obtain baseline data on hand hygiene compliance within the ICU. This baseline data will be used in a gap analysis to identify causes of non-compliance and develop interventions to promote a better environment of care. The project focuses on the implementation of multiple interventions in the forms of engineered controls,  enhanced education of staff and policy changes-all of which are driven by the collection of both quantitative and quantitative data. I have a strong interest in infection control and disease prevention and have found this work to be both informative and rewarding. 



```{=html}
<div  style="margin: 30px; text-align: center;">
<a class="btn btn-primary" href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/" role="button" target="_blank" style="padding: 15px 30px;">View the tutorial for this template (+ download link)</a>
</div>
```
